<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>HyperGeo</groupId>
  <artifactId>HyperGeo</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <build>
    <sourceDirectory>HyperGeo/src</sourceDirectory>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <release>21</release>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <properties>
	<jzyversion>2.2.0</jzyversion>
  </properties>
  <dependencies>
	<dependency>
	    <groupId>org.mariuszgromada.math</groupId>
	    <artifactId>MathParser.org-mXparser</artifactId>
	    <version>5.2.1</version>
	</dependency>
	<dependency>
	    <groupId>org.joml</groupId>
	    <artifactId>joml</artifactId>
	    <version>1.10.5</version>
	</dependency>
	<dependency>
	    <groupId>org.jzy3d</groupId>
	    <artifactId>jzy3d-native-jogl-awt</artifactId>
	    <version>${jzyversion}</version>
	  </dependency>
	  <dependency>
	    <groupId>org.jzy3d</groupId>
	    <artifactId>jzy3d-native-jogl-swing</artifactId>
	    <version>${jzyversion}</version>
	  </dependency>
	  <dependency>
	    <groupId>org.jzy3d</groupId>
	    <artifactId>jzy3d-native-jogl-newt</artifactId>
	    <version>${jzyversion}</version>
	  </dependency>
	  <dependency>
	    <groupId>org.jzy3d</groupId>
	    <artifactId>jzy3d-native-jogl-swt</artifactId>
	    <version>${jzyversion}</version>
	  </dependency>
  </dependencies>
  <repositories>
  <repository>
    <id>jzy3d-releases</id>
    <name>Jzy3d Releases</name>
    <url>https://maven.jzy3d.org/releases/</url>
  </repository>
</repositories>
</project>